manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: baden
      url-base: https://github.com/baden
    - name: badenwork
      url-base: https://github.com/badenwork

  group-filter: [-bsec2]

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      #revision: v4.1.0
      revision: main
      clone-depth: 1
      path: zephyr
      import:
        name-allowlist:
          - cmsis_6
          - littlefs
          - lz4
          - hal_wch
          - hal_stm32
          - mcuboot
          - net-tools
        # name-blocklist:
        #   - ci-tools
        #   - hal_altera
        #   - hal_cypress
        #   - hal_infineon
        #   - hal_microchip
        #   - hal_nxp
        #   - hal_openisa
        #   - hal_silabs
        #   - hal_xtensa
        #   - hal_ti
        #   - loramac-node
        #   - net-tools
        #   - edtt
        #   - trusted-firmware-m
        #   - sof
      clone-depth: 1

    - name: zephyr-soc-nuvoton-m2354
      remote: baden
      revision: main
      path: modules/zephyr/soc/nuvoton/m2354

    - name: hal_nuvoton
      remote: badenwork
      revision: master
      path: modules/hal/nuvoton

    - name: shock-sensor-driver
      path: modules/shock-sensor-driver
      url: https://github.com/baden/zephyr-shock-sensor-driver.git
      revision: main


  self:
    west-commands: scripts/west-commands.yml
